# Generated by Django 2.2.11 on 2020-03-13 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("openhumans", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="RetrospectiveEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "certainty",
                    models.IntegerField(
                        choices=[
                            (1, "Random guess"),
                            (2, "Very uncertain"),
                            (3, "Unsure"),
                            (4, "Somewhat certain"),
                            (5, "Very certain"),
                        ]
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openhumans.OpenHumansMember",
                    ),
                ),
            ],
        )
    ]
