# Generated by Django 2.2.11 on 2020-03-13 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("retrospective", "0002_retrospectiveeventanalysis"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="retrospectiveeventanalysis", name="graph_image",
        ),
        migrations.AddField(
            model_name="retrospectiveeventanalysis",
            name="graph_type",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="retrospectiveeventanalysis",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="retrospective.RetrospectiveEvent",
            ),
        ),
    ]
