# Generated by Django 2.2.11 on 2020-03-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("retrospective", "0003_auto_20200313_1313")]

    operations = [
        migrations.AddField(
            model_name="retrospectiveevent",
            name="notes",
            field=models.TextField(default=""),
            preserve_default=False,
        )
    ]
