# Generated by Django 2.2.11 on 2020-04-09 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("quantified_flu", "0002_account_publish_symptom_reports")]

    operations = [migrations.RemoveField(model_name="account", name="public_data")]
