# Generated by Django 2.2.11 on 2020-03-20 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("openhumans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FitbitMember",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.CharField(max_length=255, null=True, unique=True)),
                ("access_token", models.CharField(max_length=512)),
                ("refresh_token", models.CharField(max_length=512)),
                ("expires_in", models.CharField(max_length=512)),
                ("scope", models.CharField(max_length=512)),
                ("token_type", models.CharField(max_length=512)),
                (
                    "last_updated",
                    models.DateTimeField(default="2020-03-13 15:14:51+00:00"),
                ),
                (
                    "last_submitted",
                    models.DateTimeField(default="2020-03-13 15:14:51+00:00"),
                ),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fitbit_member",
                        to="openhumans.OpenHumansMember",
                    ),
                ),
            ],
        ),
    ]
