# Generated by Django 2.2.11 on 2020-03-20 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("openhumans", "0001_initial"),
        ("import_data", "0002_auto_20200320_1545"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fitbitmember",
            name="last_submitted",
            field=models.DateTimeField(default="2020-03-13 18:07:20+00:00"),
        ),
        migrations.AlterField(
            model_name="fitbitmember",
            name="last_updated",
            field=models.DateTimeField(default="2020-03-13 18:07:20+00:00"),
        ),
        migrations.AlterField(
            model_name="fitbitmember",
            name="token_expires",
            field=models.DateTimeField(default="2020-03-20 18:07:20+00:00"),
        ),
        migrations.CreateModel(
            name="OuraMember",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("expiration_time", models.DateTimeField()),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oura_user",
                        to="openhumans.OpenHumansMember",
                    ),
                ),
            ],
        ),
    ]
