# Generated by Django 2.2.11 on 2020-04-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("import_data", "0003_auto_20200320_1807"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fitbitmember",
            name="last_submitted",
            field=models.DateTimeField(default="2020-04-09 11:09:27+00:00"),
        ),
        migrations.AlterField(
            model_name="fitbitmember",
            name="last_updated",
            field=models.DateTimeField(default="2020-04-09 11:09:27+00:00"),
        ),
        migrations.AlterField(
            model_name="fitbitmember",
            name="token_expires",
            field=models.DateTimeField(default="2020-04-16 11:09:27+00:00"),
        ),
    ]
