# Generated by Django 2.2.12 on 2020-05-06 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openhumans', '0001_initial'),
        ('import_data', '0004_auto_20200416_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbitmember',
            name='last_submitted',
            field=models.DateTimeField(default='2020-04-29 08:04:53+00:00'),
        ),
        migrations.AlterField(
            model_name='fitbitmember',
            name='last_updated',
            field=models.DateTimeField(default='2020-04-29 08:04:53+00:00'),
        ),
        migrations.AlterField(
            model_name='fitbitmember',
            name='token_expires',
            field=models.DateTimeField(default='2020-05-06 08:04:53+00:00'),
        ),
        migrations.CreateModel(
            name='GoogleFitMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=512)),
                ('refresh_token', models.CharField(max_length=512)),
                ('expiry_date', models.DateTimeField()),
                ('scope', models.CharField(max_length=512)),
                ('last_updated', models.DateTimeField(null=True)),
                ('last_submitted_for_update', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='googlefit_member', to='openhumans.OpenHumansMember')),
            ],
        ),
    ]
