# Generated by Django 2.2.12 on 2020-05-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0006_auto_20200519_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='garminmember',
            name='access_token_secret',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='fitbitmember',
            name='last_submitted',
            field=models.DateTimeField(default='2020-05-15 11:48:10+00:00'),
        ),
        migrations.AlterField(
            model_name='fitbitmember',
            name='last_updated',
            field=models.DateTimeField(default='2020-05-15 11:48:10+00:00'),
        ),
        migrations.AlterField(
            model_name='fitbitmember',
            name='token_expires',
            field=models.DateTimeField(default='2020-05-22 11:48:10+00:00'),
        ),
    ]
