# Generated by Django 2.2.11 on 2020-03-22 04:56

from django.db import migrations, models
import django.db.models.deletion
import reports.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("openhumans", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="SymptomReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "symptoms",
                    models.CharField(
                        choices=[
                            ("cough", "Cough"),
                            ("sore_throat", "Sore throat"),
                            ("chills", "Chills"),
                            ("body_ache", "Body ache"),
                            ("ear_ache", "Ear ache"),
                            ("nausea", "Nausea"),
                            ("stomach_ache", "Stomach ache"),
                            ("fatigue", "Fatigue"),
                            ("short_breath", "Short breath"),
                            ("headache", "Headache"),
                            ("diarrhea", "Diarrhea"),
                            ("runny nose", "Runny nose"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "fever_guess",
                    models.CharField(
                        choices=[
                            ("none", "No fever"),
                            ("low", "Maybe feverish"),
                            ("moderate", "Feverish"),
                            ("high", "High fever"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "fever",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=4),
                ),
                ("other_symptoms", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openhumans.OpenHumansMember",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("token", models.TextField(default=reports.models.create_token)),
                ("minutes_valid", models.IntegerField(default=1440)),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openhumans.OpenHumansMember",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiagnosisReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("date_tested", models.DateField()),
                (
                    "virus",
                    models.CharField(
                        choices=[
                            ("maybe_coronavirus", "suspect Coronavirus"),
                            ("coronavirus", "Coronavirus, confirmed by test"),
                            ("maybe_influenza", "suspect Influenza"),
                            ("influenza", "Influenza, confirmed by test"),
                            ("cold", "Common cold"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openhumans.OpenHumansMember",
                    ),
                ),
            ],
        ),
    ]
