# Generated by Django 2.2.11 on 2020-03-23 20:08

from django.db import migrations, models
import django.db.models.deletion
import reports.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("openhumans", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Symptom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("cough", "Cough"),
                            ("sore_throat", "Sore throat"),
                            ("chills", "Chills"),
                            ("body_ache", "Body ache"),
                            ("ear_ache", "Ear ache"),
                            ("nausea", "Nausea"),
                            ("stomach_ache", "Stomach ache"),
                            ("fatigue", "Fatigue"),
                            ("short_breath", "Short breath"),
                            ("headache", "Headache"),
                            ("diarrhea", "Diarrhea"),
                            ("runny_nose", "Runny nose"),
                            ("anosmia", "Reduced sense of smell (anosmia)"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("available", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SymptomReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "fever_guess",
                    models.CharField(
                        choices=[
                            ("none", "No fever"),
                            ("low", "Maybe feverish"),
                            ("moderate", "Feverish"),
                            ("high", "High fever"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "fever",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("other_symptoms", models.TextField(blank=True, default="")),
                (
                    "suspected_virus",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Any guess on what infection you have? (flu, cold, norovirus, coronavirus, etc.)",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("report_none", models.BooleanField(default=False)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openhumans.OpenHumansMember",
                    ),
                ),
                ("symptoms", models.ManyToManyField(to="reports.Symptom")),
            ],
        ),
        migrations.CreateModel(
            name="ReportToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("token", models.TextField(default=reports.models.create_token)),
                ("minutes_valid", models.IntegerField(default=1440)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openhumans.OpenHumansMember",
                    ),
                ),
            ],
        ),
    ]
