# Generated by Django 2.2.11 on 2020-04-03 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("reports", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="symptomreport",
            name="token",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reports.ReportToken",
            ),
        ),
        migrations.AlterField(
            model_name="symptomreport",
            name="fever_guess",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "No fever"),
                    ("low", "Maybe feverish"),
                    ("moderate", "Feverish"),
                    ("high", "High fever"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
