# Generated by Django 2.2.11 on 2020-03-23 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("reports", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Symptom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symptom",
                    models.CharField(
                        choices=[
                            ("cough", "Cough"),
                            ("sore_throat", "Sore throat"),
                            ("chills", "Chills"),
                            ("body_ache", "Body ache"),
                            ("ear_ache", "Ear ache"),
                            ("nausea", "Nausea"),
                            ("stomach_ache", "Stomach ache"),
                            ("fatigue", "Fatigue"),
                            ("short_breath", "Short breath"),
                            ("headache", "Headache"),
                            ("diarrhea", "Diarrhea"),
                            ("runny_nose", "Runny nose"),
                            ("anosmia", "Reduced sense of smell (anosmia)"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="symptomreport",
            name="report_none",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="reporttoken",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="openhumans.OpenHumansMember",
            ),
        ),
        migrations.AlterField(
            model_name="symptomreport",
            name="fever",
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name="symptomreport",
            name="fever_guess",
            field=models.CharField(
                choices=[
                    ("none", "No fever"),
                    ("low", "Maybe feverish"),
                    ("moderate", "Feverish"),
                    ("high", "High fever"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="symptomreport",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="symptomreport",
            name="other_symptoms",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RemoveField(model_name="symptomreport", name="symptoms"),
        migrations.AddField(
            model_name="symptomreport",
            name="symptoms",
            field=models.ManyToManyField(to="reports.Symptom"),
        ),
    ]
