# Generated by Django 2.2.11 on 2020-04-09 21:11

from django.db import migrations, models
import django.db.models.deletion


def create_through_relations(apps, schema_editor):
    Symptom = apps.get_model("reports", "Symptom")
    SymptomReport = apps.get_model("reports", "SymptomReport")
    SymptomReportSymptomItem = apps.get_model("reports", "SymptomReportSymptomItem")

    symptom_choices = Symptom._meta.get_field("label").choices
    symptoms_by_label = {
        x[0]: Symptom.objects.get_or_create(label=x[0])[0] for x in symptom_choices
    }

    for report in SymptomReport.objects.all():
        symptom_intensities = {x: 0 for x in report.symptoms.all()}

        # map existing symptom reports to have intensity of 2
        for symptom in report.symptoms.all():
            SymptomReportSymptomItem(report=report, symptom=symptom, intensity=2).save()

        # create remainder with default intensity of 0
        for symptom_label in symptoms_by_label:
            SymptomReportSymptomItem.objects.get_or_create(
                report=report, symptom_id=symptoms_by_label[symptom_label].id
            )


class Migration(migrations.Migration):

    dependencies = [("reports", "0002_auto_20200403_0022")]

    operations = [
        migrations.CreateModel(
            name="SymptomReportSymptomItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intensity",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, "A little"),
                            (2, "Somewhat"),
                            (3, "Quite a bit"),
                            (4, "Very much"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.SymptomReport",
                    ),
                ),
                (
                    "symptom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.Symptom",
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            create_through_relations, reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(model_name="symptomreport", name="symptoms"),
    ]
