# Generated by Django 2.2.11 on 2020-03-20 06:03

from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [("openhumans", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="CheckinSchedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("timezone", timezone_field.fields.TimeZoneField()),
                ("time", models.TimeField()),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openhumans.OpenHumansMember",
                    ),
                ),
            ],
        )
    ]
